export default [
  "Laravel",
  "Vue.js",
  "PHP",
  "JavaScript",
  "GraphQL",
  "MySQL",
  "Storyblok CMS",
  "Redis",
  "Git",
  "RESTful APIs",
  "Docker",
  "Agile & Scrum",
  "Software Architecture",
  "Design Patterns (Factory, Repository, etc.)",
];
